def COLOR_MAP = ['SUCCESS': 'good', 'FAILURE': 'danger', 'UNSTABLE': 'danger', 'ABORTED': 'danger']

pipeline {
    agent any
    tools { nodejs "nodejs-10.0.0" }
    environment {
        DATE = new Date().format('yy.M')
        TAG = "${DATE}.${BUILD_NUMBER}"
    }
    stages {
        stage('Build') {
            steps {
	            sh 'npm install'
                sh 'npm run build'
            }
        }
        stage('Docker Build') {
            steps {
                script {
                    docker.build("prasanabala123/easyclaim-frontend:b1")
                }
            }
        }
	    stage('Pushing Docker Image to Dockerhub') {
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', 'docker_credential') {
                        docker.image("prasanabala123/easyclaim-frontend:b1").push()
                        docker.image("prasanabala123/easyclaim-frontend:b1").push("32011")
                    }
                }
            }
        }
    }
}
